# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: RoboticArm

on:
  push:
    branches: [ main, testing_roboarm, kuksov]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install Pillow
        pip install numpy
        pip install tensorflow
        pip install keras
        pip install pyusb
        pip install pathlib2
        pip install matplotlib
        pip install pytest-shutil

        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with pytest
      run: |
          pytest --ignore-glob=source/test/python2/stereovision_testing_module --ignore-glob=source/test/python3/image_processing_module/test_tutorial.py --ignore-glob=source/test/python3/image_processing_module/test_fine_tuning.py --ignore-glob=source/test/python3/image_processing_module/test_compress_images.py
